export const GET_CATEGORIES_START='GET_CATEGORIES_START';

export const GET_CATEGORIES_FINISH='GET_CATEGORIES_FINISH';

export const SEND_LOCATION_START='SEND_LOCATION_START';
export const SEND_LOCATION_FINISH='SEND_LOCATION_FINISH';